// <auto-generated />
using CakeShopApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CakeShopApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207122350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CakeShopApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("StockQty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "111",
                            Name = "Chocolate Cake",
                            Price = 1500m,
                            PricePerKg = 0m,
                            StockQty = 10m,
                            Type = "fixed"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "222",
                            Name = "Ribbon Cake",
                            Price = 0m,
                            PricePerKg = 2500m,
                            StockQty = 20m,
                            Type = "weight"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "333",
                            Name = "Cup Cake",
                            Price = 300m,
                            PricePerKg = 0m,
                            StockQty = 25m,
                            Type = "fixed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
